// Code generated by ifacemaker; DO NOT EDIT.

package metalcloud


import metalcloud "github.com/metalsoft-io/metal-cloud-sdk-go"



import metalcloud "github.com/metalsoft-io/metal-cloud-sdk-go"


// MetalCloudClient interface used for mocking and abstracting the backend
type MetalCloudClient interface {
}
