kind: DatacenterWithConfig
apiVersion: 1.0
datacenter:
  id: 1
  name: test-dc-100
  displayName: test-dc-100
  isMaster: false
  isMaintenance: true
  type: metal_cloud
  createdTimestamp: "2024-04-17T16:19:51Z"
  updatedTimestamp: "2024-04-17T16:19:51Z"
  isHidden: false
  tags:
  - 5o6W758WZN
  - SrvMdF2H4F
  - gui_n431zmxxd3
  - gui_zsc3brt593
  - gui_8ipptyni0w
  - gui_9oj3wtofns
  - gui_97hdjhl5ua
  - gui_v8er9lscgw
  - gui_ounedm7yxv
datacenterConfig:
  BSIMachinesSubnetIPv4CIDR: 172.31.255.254/30
  BSIVRRPListenIPv4: 172.31.255.254
  BSIMachineListenIPv4List:
  - 172.31.255.254
  BSIExternallyVisibleIPv4: 10.255.131.5
  repoURLRoot: http://repointegrationpublic.bigstepcloud.com
  repoURLRootQuarantineNetwork: http://repointegrationpublic.bigstepcloud.com
  SANRoutedSubnet: 100.96.0.0/16
  NTPServers:
  - 45.55.58.103
  DNSServers:
  - 10.255.231.44
  - 10.255.231.45
  KMS: 84.40.58.70:1688
  TFTPServerWANVRRPListenIPv4: 172.31.255.254
  dataLakeEnabled: false
  latitude: 51.497938
  longitude: -0.1840123
  address: dsfdsf
  serverRegisterUsingGeneratedIPMICredentialsEnabled: true
  serverRegisterUsingProvidedIPMICredentialsEnabled: false
  switchProvisioner:
    ASNRanges: []
    LAGRanges:
    - 1960-2000
    LANVLANRange: 234-299
    MLAGRanges:
    - 30-90
    SANVLANRange: 300-399
    SANVNIPrefix: 2
    VRFL3VNIPrefix: 9
    VRFVLANRanges: []
    WANVLANRange: 100-199
    WANVNIPrefix: 1
    allocateDefaultLANVLAN: true
    allocateDefaultSANVLAN: true
    allocateDefaultWANVLAN: true
    disableQuarantineNetwork: false
    leafSwitchesHaveMLAGPairs: false
    preventCleanupForVLANs:
    - 4094
    - 1
    preventCleanupForVLANsFromExternalConnectionUplinks:
    - 4094
    - 1
    preventCleanupForVRFs: []
    preventUsageOfVLANs:
    - 4000
    - 1
    preventUsageOfVRFs: []
    quarantineVLANID: 5
    storageHasSeparateFabric: true
    type: EVPNVXLANL2Provisioner
    zeroTouchRegistrationEnabled: false
  enableTenantAccessToIPMI: true
  allowVLANOverrides: true
  allowNetworkProfiles: true
  enableServerRegistrationStartedByInBandDHCP: true
  extraInternalIPsPerSubnet: 2
  extraInternalIPsPerSANSubnet: 1
  serverRAIDConfigurationEnabled: true
  webProxy: null
  isKubernetesDeployment: true
  allowInstanceArrayFirmwarePolicies: true
  provisionUsingTheQuarantineNetwork: true
  enableDHCPRelaySecurityForQuarantineNetwork: false
  enableDHCPRelaySecurityForClientNetworks: false
  enableDHCPBMCMACAddressWhitelist: true
  dhcpBMCMACAddressWhitelist: []
  defaultServerCleanupPolicyID: 0
  defaultWANNetworkProfileID: 0
  defaultDeploymentMechanism: virtual_media
  defaultCleanupAndRegistrationMechanism: bmc
  NFSServer: 10.255.131.5
  Option82ToIPMapping:
    Eth1/1: 10.255.129.1
    asdasda: 10.20.30.40
    vlan1-ethernet1/1/24: 10.255.148.25