kind: SwitchDevice
apiVersion: 1.0
id: 9946
datacenterName: private-dc-794-bsi-1etqkj
provisionerType: evpnvxlanl2
provisionerPosition: other
managementUsername: yflYwqX4GY
managementPassword: zSiEu8mada
managementAddress: 10.3.15.83
managementPort: 22
managementProtocol: ssh
managementMACAddress: 05:17:08:4b:53:1d
primaryWANIPv4SubnetPrefixSize: 22
primarySANSubnetPrefixSize: 21
description: EL7wORkzaO
country: US
city: New York
netDatacenter: New York
datacenterRoom: New York
datacenterRack: New York
requiresOSInstall: false
isBorderDevice: false
isStorageSwitch: true
isGateway: false