kind: SwitchDevice
apiVersion: 1.0
id: 95
identifierString: R3R11-U30-Leaf4
datacenterName: datacenter1
provisionerType: vpls
provisionerPosition: tor
driver: hp5800
managementUsername: test
managementPassword: test
managementAddress: 192.168.137.2
managementPort: 21
managementProtocol: ssh
managementAddressMask: 255.255.255.1
managementAddressGateway: 192.168.137.3
managementMACAddress: 00:A0:C9:14:C8:26
primaryWANIPv4SubnetPool: 192.168.0.1
primaryWANIPv4SubnetPrefixSize: 23
primaryWANIPv6SubnetPoolID: 129
primaryWANIPv6SubnetCIDR: fd1f:8bbb:56b3:800:0:0:0:1/54
primarySANSubnetPool: 192.168.0.1
primarySANSubnetPrefixSize: 22
quarantineSubnetStart: 192.168.1.2
quarantineSubnetEnd: 192.168.1.254
quarantineSubnetPrefixSize: 24
quarantineSubnetGateway: 192.168.1.1
description: ggg
country: UKgg
city: Readinggg
netDatacenter: Amito-DC1ggg
datacenterRoom: Room-1gg
datacenterRack: A2gg
rackPositionUpperUnit: 32
rackPositionLowerUnit: 33
serialNumber: CN34FHC0765
requiresOSInstall: false
isBorderDevice: false
isStorageSwitch: false
isGateway: true
networkTypesAllowed:
- wan
- san
- lan
- quarantine
