// Code generated by ifacemaker; DO NOT EDIT.

package interfaces


import metalcloud "github.com/bigstepinc/metal-cloud-sdk-go"




// MetalCloudClient interface used for mocking and abstracting the backend
type MetalCloudClient interface {
	//DriveArrays retrieves the list of drives arrays of an infrastructure
	DriveArrays(infrastructureID int) (*map[string]metalcloud.DriveArray, error)
	//DriveArraysByLabel retrieves the list of drives arrays of an infrastructure
	DriveArraysByLabel(infrastructureLabel string) (*map[string]metalcloud.DriveArray, error)
	//DriveArrayGet retrieves a metalcloud.DriveArray object with specified ids
	DriveArrayGet(driveArrayID int) (*metalcloud.DriveArray, error)
	//DriveArrayGetByLabel retrieves a metalcloud.DriveArray object with specified ids
	DriveArrayGetByLabel(driveArrayLabel string) (*metalcloud.DriveArray, error)
	//DriveArrayCreate creates a drive array. Requires deploy.
	DriveArrayCreate(infrastructureID int, driveArray metalcloud.DriveArray) (*metalcloud.DriveArray, error)
	//DriveArrayCreateByLabel creates a drive array. Requires deploy.
	DriveArrayCreateByLabel(infrastructureLabel string, driveArray metalcloud.DriveArray) (*metalcloud.DriveArray, error)
	//DriveArrayEdit alters a deployed drive array. Requires deploy.
	DriveArrayEdit(driveArrayID int, driveArrayOperation metalcloud.DriveArrayOperation) (*metalcloud.DriveArray, error)
	//DriveArrayEditByLabel alters a deployed drive array. Requires deploy.
	DriveArrayEditByLabel(driveArrayLabel string, driveArrayOperation metalcloud.DriveArrayOperation) (*metalcloud.DriveArray, error)
	//DriveArrayDelete deletes a Drive Array with specified id
	DriveArrayDelete(driveArrayID int) error
	//DriveArrayDeleteByLabel deletes a Drive Array with specified id
	DriveArrayDeleteByLabel(driveArrayLabel string) error
	//InfrastructureCreate creates an infrastructure
	InfrastructureCreate(infrastructure metalcloud.Infrastructure) (*metalcloud.Infrastructure, error)
	//Infrastructures returns a list of infrastructures
	Infrastructures() (*map[string]metalcloud.Infrastructure, error)
	//InfrastructureEdit alters an infrastructure
	InfrastructureEdit(infrastructureID int, infrastructureOperation metalcloud.InfrastructureOperation) (*metalcloud.Infrastructure, error)
	//InfrastructureEditByLabel alters an infrastructure
	InfrastructureEditByLabel(infrastructureLabel string, infrastructureOperation metalcloud.InfrastructureOperation) (*metalcloud.Infrastructure, error)
	//InfrastructureDelete deletes an infrastructure and all associated elements. Requires deploy
	InfrastructureDelete(infrastructureID int) error
	//InfrastructureDeleteByLabel deletes an infrastructure and all associated elements. Requires deploy
	InfrastructureDeleteByLabel(infrastructureLabel string) error
	//InfrastructureOperationCancel reverts (undos) alterations done before deploy
	InfrastructureOperationCancel(infrastructureID int) error
	//InfrastructureOperationCancelByLabel reverts (undos) alterations done before deploy
	InfrastructureOperationCancelByLabel(infrastructureLabel string) error
	//InfrastructureDeploy initiates a deploy operation that will apply all registered changes for the respective infrastructure
	InfrastructureDeploy(infrastructureID int, shutdownOptions metalcloud.ShutdownOptions, allowDataLoss bool, skipAnsible bool) error
	//InfrastructureDeployByLabel initiates a deploy operation that will apply all registered changes for the respective infrastructure
	InfrastructureDeployByLabel(infrastructureLabel string, shutdownOptions metalcloud.ShutdownOptions, allowDataLoss bool, skipAnsible bool) error
	//InfrastructureGet returns a specific infrastructure by id
	InfrastructureGet(infrastructureID int) (*metalcloud.Infrastructure, error)
	//InfrastructureGetByLabel returns a specific infrastructure by id
	InfrastructureGetByLabel(infrastructureLabel string) (*metalcloud.Infrastructure, error)
	//InfrastructureUserLimits returns user metadata
	InfrastructureUserLimits(infrastructureID int) (*map[string]interface{}, error)
	//InfrastructureUserLimitsByLabel returns user metadata
	InfrastructureUserLimitsByLabel(infrastructureLabel string) (*map[string]interface{}, error)
	//InstanceArrayInterfaceAttachNetwork attaches an InstanceArrayInterface to a metalcloud.Network
	InstanceArrayInterfaceAttachNetwork(instanceArrayID int, instanceArrayInterfaceIndex int, networkID int) (*metalcloud.InstanceArray, error)
	//InstanceArrayInterfaceDetach detaches an InstanceArrayInterface from any metalcloud.Network element that is attached to.
	InstanceArrayInterfaceDetach(instanceArrayID int, instanceArrayInterfaceIndex int) (*metalcloud.InstanceArray, error)
	//InstanceArrayGet returns an metalcloud.InstanceArray with specified id
	InstanceArrayGet(instanceArrayID int) (*metalcloud.InstanceArray, error)
	//InstanceArrayGetByLabel returns an metalcloud.InstanceArray with specified id
	InstanceArrayGetByLabel(instanceArrayLabel string) (*metalcloud.InstanceArray, error)
	//InstanceArrays returns list of instance arrays of specified infrastructure
	InstanceArrays(infrastructureID int) (*map[string]metalcloud.InstanceArray, error)
	//InstanceArraysByLabel returns list of instance arrays of specified infrastructure
	InstanceArraysByLabel(infrastructureLabel string) (*map[string]metalcloud.InstanceArray, error)
	//InstanceArrayCreate creates an instance array (colletion of identical instances). Requires Deploy.
	InstanceArrayCreate(infrastructureID int, instanceArray metalcloud.InstanceArray) (*metalcloud.InstanceArray, error)
	//InstanceArrayCreateByLabel creates an instance array (colletion of identical instances). Requires Deploy.
	InstanceArrayCreateByLabel(infrastructureLabel string, instanceArray metalcloud.InstanceArray) (*metalcloud.InstanceArray, error)
	//InstanceArrayEdit alterns a deployed instance array. Requires deploy.
	InstanceArrayEdit(instanceArrayID int, instanceArrayOperation metalcloud.InstanceArrayOperation, bSwapExistingInstancesHardware *bool, bKeepDetachingDrives *bool, objServerTypeMatches *[]metalcloud.ServerType, arrInstancesToBeDeleted *[]int) (*metalcloud.InstanceArray, error)
	//InstanceArrayEditByLabel alterns a deployed instance array. Requires deploy.
	InstanceArrayEditByLabel(instanceArrayLabel string, instanceArrayOperation metalcloud.InstanceArrayOperation, bSwapExistingInstancesHardware *bool, bKeepDetachingDrives *bool, objServerTypeMatches *[]metalcloud.ServerType, arrInstancesToBeDeleted *[]int) (*metalcloud.InstanceArray, error)
	//InstanceArrayDelete deletes an instance array. Requires deploy.
	InstanceArrayDelete(instanceArrayID int) error
	//InstanceArrayDeleteByLabel deletes an instance array. Requires deploy.
	InstanceArrayDeleteByLabel(instanceArrayLabel string) error
	//GetUserEmail returns the user configured for this connection
	GetUserEmail() string
	//GetEndpoint returns the endpoint configured for this connection
	GetEndpoint() string
	//NetworkGet retrieves a network object
	NetworkGet(networkID int) (*metalcloud.Network, error)
	//NetworkGetByLabel retrieves a network object
	NetworkGetByLabel(networkLabel string) (*metalcloud.Network, error)
	//Networks returns a list of all network objects of an infrastructure
	Networks(infrastructureID int) (*map[string]metalcloud.Network, error)
	//NetworksByLabel returns a list of all network objects of an infrastructure
	NetworksByLabel(infrastructureLabel string) (*map[string]metalcloud.Network, error)
	//NetworkCreate creates a network
	NetworkCreate(infrastructureID int, network metalcloud.Network) (*metalcloud.Network, error)
	//NetworkCreateByLabel creates a network
	NetworkCreateByLabel(infrastructureLabel string, network metalcloud.Network) (*metalcloud.Network, error)
	//NetworkEdit applies a change to an existing network
	NetworkEdit(networkID int, networkOperation metalcloud.NetworkOperation) (*metalcloud.Network, error)
	//NetworkEditByLabel applies a change to an existing network
	NetworkEditByLabel(networkLabel string, networkOperation metalcloud.NetworkOperation) (*metalcloud.Network, error)
	//NetworkDelete deletes a network.
	NetworkDelete(networkID int) error
	//NetworkDeleteByLabel deletes a network.
	NetworkDeleteByLabel(networkLabel string) error
	//NetworkJoin merges two specified metalcloud.Network objects.
	NetworkJoin(networkID int, networkToBeDeletedID int) error
	//NetworkJoinByLabel merges two specified metalcloud.Network objects.
	NetworkJoinByLabel(networkLabel string, networkToBeDeletedID int) error
	//ServerTypesMatchHardwareConfiguration Retrieves a list of server types that match the provided hardware configuration. The function does not check for availability, only compatibility, so physical servers associated with the returned server types might be unavailable.
	ServerTypesMatchHardwareConfiguration(datacenterName string, hardwareConfiguration metalcloud.HardwareConfiguration) (*map[int]metalcloud.ServerType, error)
	//ServerTypeDatacenter retrieves all the server type IDs for servers found in a specified Datacenter
	ServerTypeDatacenter(datacenterName string) (*[]int, error)
	//ServerTypes retrieves all metalcloud.ServerType objects from the database.
	ServerTypes(datacenterName string, bOnlyAvailable bool) (*map[int]metalcloud.ServerType, error)
	//ServerTypeGet retrieves a server type by id
	ServerTypeGet(serverTypeID int) (*metalcloud.ServerType, error)
	//ServerTypeGetByLabel retrieves a server type by id
	ServerTypeGetByLabel(serverTypeLabel string) (*metalcloud.ServerType, error)
	//ServerTypesMatches matches available servers with a certain Instance&#39;s configuration, using the properties specified in the objHardwareConfiguration object, and returns the number of compatible servers for each server_type_id.
	ServerTypesMatches(infrastructureID int, hardwareConfiguration metalcloud.HardwareConfiguration, instanceArrayID *int, bAllowServerSwap bool) (*map[string]metalcloud.ServerType, error)
	//ServerTypesMatchesByLabel matches available servers with a certain Instance&#39;s configuration, using the properties specified in the objHardwareConfiguration object, and returns the number of compatible servers for each server_type_id.
	ServerTypesMatchesByLabel(infrastructureLabel string, hardwareConfiguration metalcloud.HardwareConfiguration, instanceArrayID *int, bAllowServerSwap bool) (*map[string]metalcloud.ServerType, error)
	//VolumeTemplates retrives the list of available templates
	VolumeTemplates() (*map[string]metalcloud.VolumeTemplate, error)
	//VolumeTemplateGet returns the specified volume template
	VolumeTemplateGet(volumeTemplateID int) (*metalcloud.VolumeTemplate, error)
	//VolumeTemplateGetByLabel returns the specified volume template
	VolumeTemplateGetByLabel(volumeTemplateLabel string) (*metalcloud.VolumeTemplate, error)
}
