package command

const ADMIN_ACCESS = "admin_access"
const DATACENTER_READ = "datacenter_read"
const DATACENTER_WRITE = "datacenter_write"
const FIRMWARE_UPGRADE_READ = "firmware_upgrade_read"
const FIRMWARE_UPGRADE_WRITE = "firmware_upgrade_write"
const FIRMWARE_BASELINES_READ = "firmware_baselines_read"
const FIRMWARE_BASELINES_WRITE = "firmware_baselines_write"
const JOB_QUEUE_READ = "job_queue_read"
const JOB_QUEUE_WRITE = "job_queue_write"
const TEMPLATES_READ = "templates_read"
const TEMPLATES_WRITE = "templates_write"
const SERVERS_READ = "servers_read"
const SERVERS_WRITE = "servers_write"
const STORAGE_READ = "storage_read"
const STORAGE_WRITE = "storage_write"
const SUBNETS_READ = "subnets_read"
const SUBNETS_WRITE = "subnets_write"
const SWITCHES_READ = "switches_read"
const SWITCHES_WRITE = "switches_write"
const USERS_AND_PERMISSIONS_READ = "users_and_permissions_read"
const USERS_AND_PERMISSIONS_WRITE = "users_and_permissions_write"
const NETWORK_PROFILES_READ = "network_profiles_read"
const NETWORK_PROFILES_WRITE = "network_profiles_write"
const WORKFLOWS_READ = "workflows_read"
const WORKFLOWS_WRITE = "workflows_write"
